# permissions for end users to view azurevmschedulerstarts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: azurevmschedulerstart-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator
    app.kubernetes.io/part-of: vm-scheduler-operator
    app.kubernetes.io/managed-by: kustomize
  name: azurevmschedulerstart-viewer-role
rules:
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstarts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstarts/status
  verbs:
  - get
